### ISSUE TITLE
UTF-8 not handled while writing

### ISSUE THREAD

**Issue by laanwj** [jgarzik/univalue#16]
UTF-8 is not handled while writing strings in `json_escape`. The result of this is that unicode sequences like '\u1234' will be expanded to their UTF-8 equivalent on a roundtrip, and re-encoded as multiple unicode characters `\u00XX\u00XX...` which is not correct.

This could be handled:

If the input/output is UTF-8 encoded, UTF-8 sequences in strings can be passed through on output without any processing (according to RFC 4627 "All Unicode characters may be placed within the quotation marks except for the characters that must be escaped: quotation mark, reverse solidus, and the control characters (U+0000 through U+001F).")

From RFC 4627:
```
JSON text SHALL be encoded in Unicode.  The default encoding is
UTF-8.
```

**Comment by apoelstra** [comment]
To be consistent with https://github.com/apoelstra/strason the behaviour should be:

* For the appropriate escape characters (\n, \r, \b, \f, \", \\) use those. (It's allowable to escape / as well but I don't.)
* For isprint ASCII characters, pass through.
* For everything else, encode as UTF-16BE and use \uXXXX.
