### ISSUE TITLE
No support for wstring 

### ISSUE THREAD

**Issue by BlockMechanic** [jgarzik/univalue#40]
Not sure if this was designed specifically for use with bitcoin related services only, but support for wstrings and other w* types would make it a great drop in replacement for the old json spirit many services just copied from pre-univalue sources.

**Comment by jgarzik** [comment]
@BlockMechanic Do you have a link to an example user, for test purposes?

**Comment by jgarzik** [comment]
Happy to consider and re-open this issue, if a link to an example can be provided.
