### ISSUE TITLE
Please issue new release 1.0.4

### ISSUE THREAD

**Issue by jonassmedegaard** [jgarzik/univalue#54]
Hi,

It seems Bitcoin has run of with a recent development snapshot of univalue and treated it as release 1.0.4.

Please formally issue a release 1.0.4, for those (like Debian) who prefer system-shared libraries tracking single unified upstream projects.

(or document if in fact _this_ is a fork and the proper source is what is maintained by the Bitcoin project).

**Comment by jonassmedegaard** [comment]
Here's the detail in Bitcoin: https://github.com/bitcoin/bitcoin/pull/12666

**Comment by jgarzik** [comment]
Done on August 31 in https://github.com/jgarzik/univalue/commit/88967f658663654a67f1cda93ca6f99de1f7c91f
